// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniformesSystem.Database;

#nullable disable

namespace UniformesSystem.Database.Migrations
{
    [DbContext(typeof(UniformesDbContext))]
    [Migration("20250704161918_AddStoredProceduresAndViews")]
    partial class AddStoredProceduresAndViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniformesSystem.Database.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("id_grupo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_empleado");

                    b.HasKey("EmployeeId");

                    b.HasIndex("GroupId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.EmployeeType", b =>
                {
                    b.Property<int>("EmployeeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeTypeId"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("EmployeeTypeId");

                    b.ToTable("EmployeeTypes", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeTypeId = 1,
                            Type = "Sindicalizados"
                        },
                        new
                        {
                            EmployeeTypeId = 2,
                            Type = "Confianza"
                        });
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_grupo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int>("EmployeeTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("grupo");

                    b.HasKey("GroupId");

                    b.HasIndex("EmployeeTypeId");

                    b.ToTable("Groups", (string)null);

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            EmployeeTypeId = 1,
                            Name = "A"
                        },
                        new
                        {
                            GroupId = 2,
                            EmployeeTypeId = 1,
                            Name = "B"
                        },
                        new
                        {
                            GroupId = 3,
                            EmployeeTypeId = 1,
                            Name = "C"
                        },
                        new
                        {
                            GroupId = 4,
                            EmployeeTypeId = 1,
                            Name = "D"
                        },
                        new
                        {
                            GroupId = 5,
                            EmployeeTypeId = 1,
                            Name = "E"
                        },
                        new
                        {
                            GroupId = 6,
                            EmployeeTypeId = 2,
                            Name = "Z"
                        });
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.Inventory", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("SizeId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.ItemType", b =>
                {
                    b.Property<int>("ItemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemTypeId"));

                    b.Property<bool>("IsUniversal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemTypeId");

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.ItemTypeEmployeeType", b =>
                {
                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.HasKey("ItemTypeId", "EmployeeTypeId");

                    b.HasIndex("EmployeeTypeId");

                    b.ToTable("ItemTypeEmployeeTypes");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"));

                    b.Property<int>("System")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SizeId");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.WarehouseMovement", b =>
                {
                    b.Property<int>("WarehouseMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseMovementId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("MovementType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarehouseMovementId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WarehouseMovements");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.WarehouseMovementDetail", b =>
                {
                    b.Property<int>("WarehouseMovementDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseMovementDetailId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseMovementId")
                        .HasColumnType("int");

                    b.HasKey("WarehouseMovementDetailId");

                    b.HasIndex("ItemId");

                    b.HasIndex("WarehouseMovementId");

                    b.ToTable("WarehouseMovementDetails");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.Employee", b =>
                {
                    b.HasOne("UniformesSystem.Database.Models.Group", "Group")
                        .WithMany("Employees")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.Group", b =>
                {
                    b.HasOne("UniformesSystem.Database.Models.EmployeeType", "EmployeeType")
                        .WithMany("Groups")
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.Inventory", b =>
                {
                    b.HasOne("UniformesSystem.Database.Models.Item", "Item")
                        .WithMany("Inventories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.Item", b =>
                {
                    b.HasOne("UniformesSystem.Database.Models.ItemType", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniformesSystem.Database.Models.Size", "Size")
                        .WithMany("Items")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemType");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.ItemTypeEmployeeType", b =>
                {
                    b.HasOne("UniformesSystem.Database.Models.EmployeeType", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniformesSystem.Database.Models.ItemType", "ItemType")
                        .WithMany("ItemTypeEmployeeTypes")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeType");

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.WarehouseMovement", b =>
                {
                    b.HasOne("UniformesSystem.Database.Models.Employee", "Employee")
                        .WithMany("WarehouseMovements")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.WarehouseMovementDetail", b =>
                {
                    b.HasOne("UniformesSystem.Database.Models.Item", "Item")
                        .WithMany("WarehouseMovementDetails")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniformesSystem.Database.Models.WarehouseMovement", "WarehouseMovement")
                        .WithMany("Details")
                        .HasForeignKey("WarehouseMovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("WarehouseMovement");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.Employee", b =>
                {
                    b.Navigation("WarehouseMovements");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.EmployeeType", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.Group", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.Item", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("WarehouseMovementDetails");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.ItemType", b =>
                {
                    b.Navigation("ItemTypeEmployeeTypes");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.Size", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("UniformesSystem.Database.Models.WarehouseMovement", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
